package desperado.com.daily.data.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import desperado.com.daily.data.bean.NewsExtraBean;
import desperado.com.daily.data.bean.LatestNewBean;
import desperado.com.daily.data.bean.NewsDetailBean;
import desperado.com.daily.data.bean.ThemeListBean;

import desperado.com.daily.data.greendao.NewsExtraBeanDao;
import desperado.com.daily.data.greendao.LatestNewBeanDao;
import desperado.com.daily.data.greendao.NewsDetailBeanDao;
import desperado.com.daily.data.greendao.ThemeListBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsExtraBeanDaoConfig;
    private final DaoConfig latestNewBeanDaoConfig;
    private final DaoConfig newsDetailBeanDaoConfig;
    private final DaoConfig themeListBeanDaoConfig;

    private final NewsExtraBeanDao newsExtraBeanDao;
    private final LatestNewBeanDao latestNewBeanDao;
    private final NewsDetailBeanDao newsDetailBeanDao;
    private final ThemeListBeanDao themeListBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsExtraBeanDaoConfig = daoConfigMap.get(NewsExtraBeanDao.class).clone();
        newsExtraBeanDaoConfig.initIdentityScope(type);

        latestNewBeanDaoConfig = daoConfigMap.get(LatestNewBeanDao.class).clone();
        latestNewBeanDaoConfig.initIdentityScope(type);

        newsDetailBeanDaoConfig = daoConfigMap.get(NewsDetailBeanDao.class).clone();
        newsDetailBeanDaoConfig.initIdentityScope(type);

        themeListBeanDaoConfig = daoConfigMap.get(ThemeListBeanDao.class).clone();
        themeListBeanDaoConfig.initIdentityScope(type);

        newsExtraBeanDao = new NewsExtraBeanDao(newsExtraBeanDaoConfig, this);
        latestNewBeanDao = new LatestNewBeanDao(latestNewBeanDaoConfig, this);
        newsDetailBeanDao = new NewsDetailBeanDao(newsDetailBeanDaoConfig, this);
        themeListBeanDao = new ThemeListBeanDao(themeListBeanDaoConfig, this);

        registerDao(NewsExtraBean.class, newsExtraBeanDao);
        registerDao(LatestNewBean.class, latestNewBeanDao);
        registerDao(NewsDetailBean.class, newsDetailBeanDao);
        registerDao(ThemeListBean.class, themeListBeanDao);
    }
    
    public void clear() {
        newsExtraBeanDaoConfig.clearIdentityScope();
        latestNewBeanDaoConfig.clearIdentityScope();
        newsDetailBeanDaoConfig.clearIdentityScope();
        themeListBeanDaoConfig.clearIdentityScope();
    }

    public NewsExtraBeanDao getNewsExtraBeanDao() {
        return newsExtraBeanDao;
    }

    public LatestNewBeanDao getLatestNewBeanDao() {
        return latestNewBeanDao;
    }

    public NewsDetailBeanDao getNewsDetailBeanDao() {
        return newsDetailBeanDao;
    }

    public ThemeListBeanDao getThemeListBeanDao() {
        return themeListBeanDao;
    }

}
