package desperado.com.daily.data.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import desperado.com.daily.data.bean.LatestNewBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LATEST_NEW_BEAN".
*/
public class LatestNewBeanDao extends AbstractDao<LatestNewBean, Void> {

    public static final String TABLENAME = "LATEST_NEW_BEAN";

    /**
     * Properties of entity LatestNewBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Date = new Property(0, String.class, "date", false, "DATE");
    }


    public LatestNewBeanDao(DaoConfig config) {
        super(config);
    }
    
    public LatestNewBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LATEST_NEW_BEAN\" (" + //
                "\"DATE\" TEXT);"); // 0: date
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LATEST_NEW_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LatestNewBean entity) {
        stmt.clearBindings();
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(1, date);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LatestNewBean entity) {
        stmt.clearBindings();
 
        String date = entity.getDate();
        if (date != null) {
            stmt.bindString(1, date);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public LatestNewBean readEntity(Cursor cursor, int offset) {
        LatestNewBean entity = new LatestNewBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // date
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LatestNewBean entity, int offset) {
        entity.setDate(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(LatestNewBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(LatestNewBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(LatestNewBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
